---
- hosts: all
  gather_facts: false

  vars_prompt:
    - name: user
      prompt: "Enter SSH user"
    - name: password
      prompt: "Enter SSH Password"

  vars:
    ansible_user: "{{ user }}"
    ansible_password: "{{ password }}"
    ansible_winrm_server_cert_validation: ignore
    ansible_connection: winrm

  tasks: 
    - name: Run Ping
      win_ping:
